/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 engine.gltf 
Author: Pilot (https://sketchfab.com/playerhack)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/jet-engine-ea66c2db873d4182b116529697d18571
Title: Jet Engine
*/

import React, { useRef, useEffect } from 'react';
import { useLoader } from '@react-three/fiber';
import { useAnimations } from '@react-three/drei';
import { createGLTFLoader } from '../../GLTFLoaderWithExtensions';
import { GLTFLoader } from 'three/examples/jsm/loaders/GLTFLoader';

const Engine = (props) => {
  const group = useRef();
  const gltf = useLoader(GLTFLoader, '/engine.gltf', createGLTFLoader);
  const { nodes, materials, animations } = gltf;
  const { actions } = useAnimations(animations, group);

 
  useEffect(() => {
    if (actions) {
      Object.values(actions).forEach((action) => action.play());
    }
  }, [actions]);

  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Sketchfab_Scene">
        <group name="Sketchfab_model" rotation={[-Math.PI / 2, 0, 0]}>
          <group name="root">
            <group name="GLTF_SceneRootNode" rotation={[Math.PI / 2, 0, 0]}>
              <group name="RootNode0_0" scale={0.01}>
                <group name="skeletal5_5">
                  <group name="GLTF_created_0">
                    <primitive object={nodes.GLTF_created_0_rootJoint} />
                    <group name="Body2_2_correction">
                      <group name="Body2_2" />
                    </group>
                    <group name="Shell3_3_correction">
                      <group name="Shell3_3" />
                    </group>
                    <group name="exhaust_and_combustor4_4_correction">
                      <group name="exhaust_and_combustor4_4" />
                    </group>
                    <skinnedMesh
                      name="Object_12"
                      geometry={nodes.Object_12.geometry}
                      material={materials.material_0}
                      skeleton={nodes.Object_12.skeleton}
                    />
                    <skinnedMesh
                      name="Object_13"
                      geometry={nodes.Object_13.geometry}
                      material={materials.material_0}
                      skeleton={nodes.Object_13.skeleton}
                    />
                    <skinnedMesh
                      name="Object_16"
                      geometry={nodes.Object_16.geometry}
                      material={materials.material_1}
                      skeleton={nodes.Object_16.skeleton}
                    />
                    <skinnedMesh
                      name="Object_19"
                      geometry={nodes.Object_19.geometry}
                      material={materials.material_2}
                      skeleton={nodes.Object_19.skeleton}
                    />
                  </group>
                </group>
              </group>
            </group>
          </group>
        </group>
      </group>
    </group>
  );
};

export default Engine;

